# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0279a373b257c846e06e359c15a34c5b"
name = "Sitemap-explorer"
application_url = "https://unruddled-mellie-stentoriously.ngrok-free.dev"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_content,write_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://unruddled-mellie-stentoriously.ngrok-free.dev/api/auth/callback"
]
